[project]
name = "FinFlow"
version = "0.1.0"
description = "A modular MCP server for financial and stock-related tools and services"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.7.1",
    "yfinance>=0.2.65",
]